
#include "template.h"

table ClassTable[] = {
"0", 0,
"absid", C_ABSID,
"list", C_LIST,
"descend", C_DESCEND,
"duplicate", C_DUPLICATE,
"root", C_ROOT,
"comment", C_COMMENT,
"label", C_LABEL,
"proc_id", C_PROC_ID,
"fun_id", C_FUN_ID,
"program", C_PROGRAM,
"declarations", C_DECLARATIONS,
"label_decl", C_LABEL_DECL,
"const_decl", C_CONST_DECL,
"type_decl", C_TYPE_DECL,
"var_decl", C_VAR_DECL,
"constant", C_CONSTANT,
"type", C_TYPE,
"typeid", C_TYPEID,
"sim_type", C_SIM_TYPE,
"st_type", C_ST_TYPE,
"field", C_FIELD,
"formal", C_FORMAL,
"statement", C_STATEMENT,
"case", C_CASE,
"caseconst", C_CASECONST,
"var", C_VAR,
"exp", C_EXP,
"decl_id", C_DECL_ID,
"hidecl_id", C_HIDECL_ID,
"blcomment", C_BLCOMMENT,
"variant", C_VARIANT,
"fld_name", C_FLD_NAME,
"passup", C_PASSUP,
"oconstant", C_OCONSTANT,
"pname", C_PNAME,
"special", C_SPECIAL,
"routname", C_ROUTNAME,
"init", C_INIT,
TAB_END, 0 };

