

static char nl[] = "";

char *ErrStrs[] = {

/* 00  */  nl,
/* 01  */  "badtok2`\"%s\" isn't valid here.  You could type \"%s\" if you did a delete",
/* 02  */  "badtoken`The input \"%s\" is not valid at the cursor.  Try the HELP key (F9)",
/* 03  */  "badsub`Subranges are only allowed in sets",
/* 04  */  "nottype`%s is not a type name, you can't put it here",
/* 05  */  "baddot`Field entry requires a record for context",
/* 06  */  "bug`BUG: appropriate list not found for comma",
/* 07  */  "procmap`You can't turn this into a procedure call",
/* 08  */  "complex`Nasty Error - expression or program too complex",
/* 09  */  "cfunc`Too many arguments to C function",
/* 10  */  "hideprogram`Can't hide the whole program",
/* 11  */  "badhide`You must select at least a whole line for hiding",
/* 12  */  "badreveal`Not a hidden part of the program",
/* 13  */  "badsellist`This command can't be applied to a list",
/* 14  */  "needrange`You must select an item or range first - see SELECT command",
/* 15  */  "needlist`Selected item must be an element in a list",
/* 16  */  nl,
/* 17  */  "unfinished`We haven't imlemented %s yet",
/* 18  */  "badspec`Type must be a named type or placeholder for absolute",
/* 19  */  "Cannot open template file",
/* 20  */  "statonl`The selected item must be a list of statements",
/* 21  */  "needblock`You may only raise a block statement",
/* 22  */  "Error while reading template file",
/* 23  */  "badspec`Can't make a specialty change to a \"%s\" node",
/* 24  */  "badimm`Can't enter immediate mode at this point",
/* 25  */  "badbp`Breakpoints should only be put on statements",
/* 26  */  "runimm`Can't do that when experimenting in immediate mode",
/* 27  */  "notsusp`Program not currently suspended",
/* 28  */  "nodecl`There is no declaration for this item",
/* 29  */  "Log - can't open file \"%s\"",
/* 30  */  "badwr2`Error writing file",
/* 31  */  "cantconv`Floating value %g can't be converted to integer",
/* 32  */  "ln`Logarithm of number <= 0.0",
/* 33  */  "sqrt`Square root of negative number",
/* 34  */  "badchr`chr: can't convert %d to character",
/* 35  */  "succ`the value %s doesn't succ",
/* 36  */  "pred`pred of %s is beyond bounds",
/* 37  */  "catlong`StrConcat makes string too long to fit",
/* 38  */  "strvar`%s must be a string variable",
/* 39  */  "strdelete`String Delete: Attempt to delete beyond bounds string: Offset %d",
/* 40  */  "stringbound`String Insert: Offset %d beyond the bounds of string %s",
/* 41  */  "stringbig`String too long",
/* 42  */  "substrbound`SubStr: requested substring beyond bounds of string",
/* 43  */  "substrfit`SubStr: Substring too long to fit in destination",
/* 44  */  "unfinished`Pack and unpack not implemented",
/* 45  */  "initrand`Random modulus must be greater than zero",
/* 46  */  "rand`You must call initrandom before using random",
/* 47  */  "newout`New - out of memory",
/* 48  */  "menu too long",
/* 49  */  "pruneall`You can't delete an entire program!",
/* 50  */  "nolist`Cannot find a list to expand",
/* 51  */  "fulllist`Can't expand list any further",
/* 52  */  "chg_decid`\"%s\" in use already",
/* 53  */  "undo`Nothing to undo",
/* 54  */  "redo`Nothing to redo",
/* 55  */  "Got to comment %x",
/* 56  */  "bug`Got funny state/node %d",
/* 57  */  "setsize`Sorry, sets element %d not allowed",
/* 58  */  "setrange`Invalid subset range %d to %d",
/* 59  */  "stop`Stop! There is an error here",
/* 60  */  "bounds`Array index %s out of bounds",
/* 61  */  "nil`Error - This pointer is NIL",
/* 62  */  "Funny symbol type %d",
/* 63  */  "intovflow`integer %s overflow",
/* 64  */  "comac`Command macros must be completed with '\n'",
/* 65  */  "conv`Failure converting \"%s\" into \"%s\", cause: %s",
/* 66  */  "loadmem`Not enough memory to load program",
/* 67  */  "badformat`bad save format (%s)",
/* 68  */  "badnode`strange type %d in file",
/* 69  */  "Can't open config file %s",
/* 70  */  "Internal error: UNIX signal %d",
/* 71  */  "Bad option %s",
/* 72  */  "opt`Invalid m#= option",
/* 73  */  "opt`macro %d out of range",
/* 74  */  "badmark`Nothing to go back to",
/* 75  */  "badmark`marks must be a letter",
/* 76  */  "badmark`mark '%c' hasn't been set",
/* 77  */  "badmark`mark '%c' has been deleted",
/* 78  */  "command line options",
/* 79  */  "memory`Out of Memory! Save your work immediately!",
/* 80  */  "divz`Floating point divide by zero",
/* 81  */  "divzero`attempted to divide by zero",
/* 82  */  "negmod`second operand of mod must be strictly positive",
/* 83  */  "execstub`Placeholders can't be executed",
/* 84  */  "Unset type in comparison",
/* 85  */  "bug`Got funny state/node %d",
/* 86  */  "Did not find child in parent in up_to_line",
/* 87  */  "badasc`Can't open file %s",
/* 88  */  "cantexec`Can't be executed in immediate mode",
/* 89  */  "bug`BUG: subrange check on non subrange %x",
/* 90  */  "subrange`Value %s is not in subrange bounds for this assignment",
/* 91  */  "badgo`Can't find the label %s",
/* 92  */  "bug`BUG:goto label not found or not in list",
/* 93  */  "badgo`A jump to label %s is not valid from here",
/* 94  */  "bnum`Badly formed number %s on input",
/* 95  */  "notread`READ/GET - file not reset for reading",
/* 96  */  "pasteof`READ/GET - tried to get past end of file",
/* 97  */  "badwrite`Sorry, you may not 'write' a complex type",
/* 98  */  "nontext`Readln - text file required",
/* 99  */  "opf`Too many active files",
/* 100 */   "rfile`This file was not initialized with 'update'",
/* 101 */   "wrfil`%s - can't open file %s",
/* 102 */   "notwrite`Put/Write - File not open for writing",
/* 103 */   "noteof`Put/Write - Not at end of file",
/* 104 */   "scrxy`ScrXY: Illegal screen query %d",
/* 105 */   "stack`Runtime stack overflow! - out of memory",
/* 106 */   "caseelse`Too many elses in case",
/* 107 */   "funnycase`Help!  Funny node in case list",
/* 108 */   "undefcase`Undefined case %s",
/* 109 */   "uninit`Attempt to use a variable that has not been initialized!",
/* 110 */   "notsusp`Your program is not currently in a suspended state",
/* 111 */   "cantresume`Sorry, unable to continue running the program",
/* 112 */   "Sorry, no saving of programs in this version",
/* 113 */   "redeclared`Symbol %s redeclared",
/* 114 */   "No match for \"%s\" found",
/* 115 */   "No previous thing to search for.",
/* 116 */   "Can't find \"%s\"",
/* 117 */   "sttype`Can't return a complex type from a function",
/* 118 */   "comp_dec: odd block %d",
/* 119 */   "caseconst`Constant isn't the same type as case value",
/* 120 */   "cantedit`Can't edit a %s as text",
/* 121 */   "syntax`Expression syntax error",
/* 122 */   "cantedit`Can't change a %s textually",
/* 123 */   "needarray`Indexing requires an array",
/* 124 */   "badindex`This index is not of the appropriate type",
/* 125 */   "needpointer`Pointer ^ requires a pointer or file variable",
/* 126 */   "baddot`dot (.) requires a record variable on the left",
/* 127 */   "setord`Set elements must be of ordinal type",
/* 128 */   "setel`This set element doesn't match the first one",
/* 129 */   "setrange`Subranges (..) may only be placed in sets",
/* 130 */   "setrange`Two ends of subrange are of differing types",
/* 131 */   "needbool`Operand of NOT must be boolean or integer",
/* 132 */   "Incompatible template file",
/* 133 */   "needbool`A Boolean (true/false) value is required here",
/* 134 */   "loopvar`Loop counter must be a simple variable",
/* 135 */   "loopvar`Loop variable must be of ordinal type",
/* 136 */   "loopbound`Start not of appropriate type",
/* 137 */   "loopbound`Finish is not of appropriate type",
/* 138 */   "repeatbool`Looping condition requires boolean value",
/* 139 */   "caseexpr`Case selector must be of ordinal type",
/* 140 */   "integerop`Operands of DIV, MOD, SHL or SHR must be integers",
/* 141 */   "boolop`Operands of AND/OR must be boolean or integer",
/* 142 */   "assign`Types on := don't match",
/* 143 */   "fileassign`Files can't be assigned",
/* 144 */   "free",
/* 145 */   "badsymbol`A symbol of this kind can't be placed here",
/* 146 */   "nrprec`Precisions (2 colons) may only be applied to real numbers",
/* 147 */   "badprec`Output precision must be integer",
/* 148 */   "badwidth`Field width must be integer",
/* 149 */   "wrformat`Improper use of format specifier (colons)",
/* 150 */   "in2`IN: Types of set and member don't match",
/* 151 */   "stub`Error - program is not finished yet",
/* 152 */   "neednumber`Operand must be integer or real",
/* 153 */   "mixedset`A set value is required here",
/* 154 */   "incompatset`Set types are not compatible",
/* 155 */   "fewargs`Routine %s has too few arguments",
/* 156 */   "needvar`This parameter must be a variable",
/* 157 */   "varptype`Var actual parameter must be of identical type to the formal",
/* 158 */   "argtype`This argument is not type-compatible with the formal parameter",
/* 159 */   "procparam`This parameter must be a user procedure",
/* 160 */   "funcparam`This parameter must be the name of a user function",
/* 161 */   "needvar`Read parameter must be a variable",
/* 162 */   "iotype`I/O argument is not of the same type as given file",
/* 163 */   "recmatch`Field name %s no longer matches the record",
/* 164 */   "fewargs`Too few arguments, should be at least %d",
/* 165 */   "manyargs`Too many arguments, must be at most %d",
/* 166 */   "Type tree of unknown symbol type %d",
/* 167 */   "foref`Symbol used before it is defined",
/* 168 */   "typ_bound:Funny node %d in typetree %x",
/* 169 */   "undeft`Undefined type name",
/* 170 */   "badset`Set elements must be in the range 0..255",
/* 171 */   "nottype`%s must be a type name",
/* 172 */   "tystub`Placeholder in type declaration",
/* 173 */   "bug`Calc_size:Bad Declaration %d in typetree %x",
/* 174 */   "badconst`An ordinal constant is expected here",
/* 175 */   "needconstnam`This name is not a constant",
/* 176 */   "varcon`Constant is not of the right type",
/* 177 */   "rangebounds`The two bounds of this range don't match",
/* 178 */   "rangeorder`Range is in the wrong order",
/* 179 */   "noroom`Not enough room to set up program output window",
/* 180 */   "nodebug`Debug window does not exist",
/* 181 */   "badwork`Workspace %s does not exist",
/* 182 */   "fragment`Can't edit code fragments (yet)",
/* 183 */   "copy`Can't copy onto the current workspace",
/* 184 */   "get`You may only insert a code portion on a placehoder",
/* 185 */   "empty`Workspace %s is empty",
/* 186 */   "inslist`You can't insert a list of things here",
/* 187 */   "badget`Can't have a %s placeholder here",
/* 188 */   "badget`You can't put %s nodes onto a %s placeholder",
/* 189 */   "badfield`%s is not a valid field of that record",
/* 190 */   "undef`Symbol \"%s\" has not been declared",
/* 191 */   "badformat`Save format %d is a later release, load at own risk",
/* 192 */   " Input - F6 for EOF ",
/* 193 */   "shell`Error executing %s",
/* 194 */   "Command finished - hit SPACE to continue",
/* 195 */   "turning on trace, file \"%s\"",
/* 196 */   "turning on unbuffered trace, file \"%s\"",
/* 197 */   "Program is running - (Ctrl-Break to halt it.)",
/* 198 */   "Program finished - hit SPACE to resume editing",
/* 199 */   "Superstep Execution",
/* 200 */   "Immediate mode execution",
/* 201 */   "noundo`Memory Recovered.  You can't UNDO past this point",
/* 202 */   "badcommand`Unknown command \"%s\"",
/* 203 */   "logging output to \"%s\"",
/* 204 */   "unfinished`Warning : No real numbers in this version",
/* 205 */   "dispose`Attempt to dispose memory already disposed of",
/* 206 */   "baddir`Bad directory",
/* 207 */   "baddir`can't cd to %s",
/* 208 */   "This will build %s \"%s\" structure",
/* 209 */   "Not enough memory for help screen",
/* 210 */   "Help on %s not available.  Check to see if Help files are on your disk",
/* 211 */   "Help on %s not available yet (%s%s)",
/* 212 */   "break`Break!",
/* 213 */   "bp`Breakpoint!",
/* 214 */   "Press the key you want to place the macro on:",
/* 215 */   "Type the macro text and press ENTER.  See the manual for details on \ codes",
/* 216 */   "macro definition aborted",
/* 217 */   "Stomp_Check fails, thenode %x, ntype is %d, full kids %d",
/* 218 */   "badsavefile`can't open save file \"%s\"",
/* 219 */   "nomac`Few macros defined. (Can't find %s) Press ESC to quit",
/* 220 */   "autosave`Automatic Save is engaged but there is no file name.",
/* 221 */   "Internal error: mfree(%X), file %s line %d",
/* 222 */   "Internal error: mfree(%x)",
/* 223 */   "lowmem`You are running out of memory.  Save your work and restart immediately!",
/* 224 */   "Comments are not allowed within expressions",
/* 225 */   "Can't insert any more text, line too long.",
/* 226 */   "Printing to file %s (sort of)",
/* 227 */   "Printing to file %s",
/* 228 */   "There is not enough memory for a menu",
/* 229 */   "numin`Input Error - Number too long",
/* 230 */   "bnum`Sorry, \"%s\" isn't a valid number, please try again",
/* 231 */   "Saving to %s",
/* 232 */   "cantopen`Can't open %s, file not saved",
/* 233 */   "A runtime error has occured (see above).  Hit SPACE to continue",
/* 234 */   "noerr`You have not had an error yet!",
/* 235 */   "fixquote can't find closing ^A",
/* 236 */   "toolong`Line on screen too long",
/* 237 */   "stomp`Previous contents of workspace %s deleted",
/* 238 */   "You haven't saved workspace %s",
/* 239 */   "Declaration under node type %d not possible",
/* 240 */   "reexpand: %x is not a list!",
/* 241 */   "contok: funny constant token %d",
/* 242 */   "Invalid declaration token %d",
/* 243 */   "wrong linelist kid",
/* 244 */   "while reading /config/apstrings",
/* 245 */   "didn't find %s",
/* 246 */   "del_decl: can't find symtab entry %x to delete in %x",
/* 247 */   "find_alice_cursor: Row %d outside of window bounds",
/* 248 */   "find_alice_cursor: Column %d out of window bounds",
/* 249 */   "find_alice_cursor : Screen has no lines on it!!!",
/* 250 */   "while reading /config/apbuiltin",
/* 251 */   "Failed to allocate storage of %u bytes",
/* 252 */   "Funny Control code %c in help file",
/* 253 */   "whatChanged/proc at root",
/* 254 */   "History list bad at start of undo",
/* 255 */   "Unknown history code %d found in history list",
/* 256 */   "History list bad at start of redo",
/* 257 */   "Error message memory overrun!",
/* 258 */   "Can't put a macro on key # %d!",
/* 259 */   "Stomp_Check fails, Tried to assign kid %d of list %x with %x when count is %d",
/* 260 */   "Tried to set kid %d of node %x with val %x",
/* 261 */   "BUG get_kidnum: Could not find %x in parent %x",
/* 262 */   "Builtin menu too long",
/* 263 */   "Can't find search start in out_line",
/* 264 */   "funny type %d in do_pushing",
/* 265 */   "not a symbol table!",
/* 266 */   "Bad suspension stack clearing immediate",
/* 267 */   "ex_class fails ",
/* 268 */   "cp not cursor in reuse",
/* 269 */   "Got l list code",
/* 270 */   "treeprint:Bad template char %d",
/* 271 */   "Can't have %d kids",
/* 272 */   "growlist(%x) on full list",
/* 273 */   "next symtab can't find next symbol",
/* 274 */   "smallerr`Segment must be Data Segment in non-large ALICE",
/* 275 */   "badint`Integer is not in range -32767..32767",
/* 276 */   "badwr3`Error writing file",
/* 277 */   "bigstruct`Structure greater or equal to 64K bytes -- shrink it!",
/* 278 */   "\"%s\" is not a valid constant",
/* 279 */   "\"%s\" is not a valid variable name",
/* 280 */   "\"%s\" is not a valid identifier",
/* 281 */   "fragment`Copying of an entire program to a workspace not permitted",
/* 282 */   "Typecheck completed.  No errors detected.",
/* 283 */   "You can enter a \"%s\" just by typing it in right now",
/* 284 */   "nohist`This operation is too involved to UNDO",
/* 285 */   "Editing operation aborted",
/* 286 */   "Your floppy with HELP appears to have been removed",
/* 287 */   "DANGER: Do NOT change floppy disks at this time",
/* 288 */   "Resumed program execution",
/* 289 */   "bug`Funny node %x in file",
/* 290 */   "bigstruct`String length out of bounds 1..255",
/* 291 */   "strplus`Concatenated string has length %d (greater than 255)",
/* 292 */   "badrtype`This is not a valid type for a range",
/* 293 */   "strcast`Strings may not be assigned to \"char\"s",
/* 294 */   "badwin`Invalid window coordinates",
/* 295 */   "badtextmode`Invalid text mode %d",
/* 296 */   "badgr`Not in graphics mode",
/* 297 */   "badcolor`Invalid colour %d (should be between 0 and %d)",
/* 298 */   "cantview`There is no graphics buffer to view",
/* 299 */   "noscrmem`Sorry, previous graphics screen lost (not enough memory to keep it)",
/* 300 */   "nitmatch`Initializer types don't match",
/* 301 */   "wsai`Should be %d elements in array initializer",
/* 302 */   "needfi`Need field initializer here",
/* 303 */   "notopen`File not open",
/* 304 */   "cto`Cursor coordinates out of bounds",
/* 305 */   "badseek`Seek/Setnext out of bounds",
/* 306 */   "trace`Too many locations under trace",
/* 307 */   "trace`Too many variable trace exceptions at once",
/* 308 */   "llib`Could not load library \"%s\"",
/* 309 */   "llib`Too many loaded libraries : %s",
/* 310 */   "needgr`graphics requires graphics adapter",
/* 311 */   "needrec`WITH requires a record variable",
/* 312 */   "genparam`This parameter must be real, ordinal or a variable",
/* 313 */   "Loading \"%s\"",
/* 314 */   "fper`Floating point error (overflow)",
/* 315 */   "strplus`Copy string position %d out of bounds",
/* 316 */   "nowinmem`Not enough memory to create output window (or dimensions out of bounds)",
/* 317 */   "badmem`Colon array index valid only with Mem array",
/* 318 */   "badmem`Absolute memory references must be made with integers",
/* 319 */   "fof`Can't have a file of files",
/* 320 */   "Corrupt symbol table",
/* 321 */   "badsavefile`Can't open library \"%s\"",
/* 322 */   "Can only copy libraries to main level",
/* 323 */   "blockio`Block I/O routine must be performed on untyped file",
/* 324 */   "toosmall`Structure too small to hold registers",
/* 325 */   "Improper use of binary library",
/* 326 */   nl,
/* 327 */   "wrformat`Segmented absolute address not allowed in small model ALICE",
/* 328 */   nl,
/* 329 */   nl,
/* 330 */   "badcode`Error - can't find mnemonic in menu",
/* 331 */   "bug`Can't find index in menu tree",
/* 332 */   "deftoolong`Default filename too long",
/* 333 */   "fullmenu`Cannot allocate any more items in menu",
/* 334 */   "fullmenu`Menu bar too wide",
/* 335 */   "illalert`Illegal Alert format",
/* 336 */   "illcoor`Illegal coordinate system",
/* 337 */   "illpatt`Illegal pattern number",
/* 338 */   "illvert`Not enough vertices in array",
/* 339 */   "manywindow`Too many windows open",
/* 340 */   "menuact`Menu cannot be active while adding items",
/* 341 */   "menuorder`Attempt to add menus in wrong order !",
/* 342 */   "mousetype`Illegal mouse type number",
/* 343 */   nl,
/* 344 */   "newwindow`Error while creating window",
/* 345 */   "nochange`Couldn't change window features",
/* 346 */   "notparm`No parameters for that event",
/* 347 */   "notparm`Not that many parameters available",
/* 348 */   "notwindow`File variable does not refer to a window",
/* 349 */   "nouser`No User Menu",
/* 350 */   "quickwindow`Illegal QuickWindow number",
/* 351 */   "sbsmall`Saveblock too small for sprite",
/* 352 */   "sdsmall`Sprite definition too small",
/* 353 */   "noinfline`There is no information line for this window",
/* 354 */   "noslider`There is no horizontal/vertical slider",
/* 355 */   "notmen`Error - pointer not allocated by NewMenuBar",
/* 356 */   "catlong`Filename variable not big enough",
/* 357 */   "catlong`Directory variable not big enough",
/* 358 */   "catlong`Answer variable not big enough",
/* 359 */   "boxsize`Menu box too large",
/* 360 */   "runexc`%s trap while running program",
/* 361 */   "Maximum of 128 points allowed",
/* 362 */   "nocpl`No compile string defined",
/* 363 */   "diffwrk`Mark is not in this workspace",
/* 364 */   "File must refer to a device",
/* 365 */   nl,
/* 366 */   "Search for: ",
/* 367 */   "[2][ScrSave buffer got stomped !][ OK ]",
/* 368 */   "[1][Error: Code not handled][ OK ]",
/* 369 */   nl,
/* 370 */   " Output ",
/* 371 */   " Running ",
/* 372 */   "[2][Sorry, Help is not|available in Low|Resolution - Use|Medium Resolution][ OK ]",
/* 373 */   "[1][Sorry, I can't find|help on that.|Make sure help files|are accessible.][ Cancel | Retry ]",
/* 374 */   " OK ",
/* 375 */   "[3][Fatal Error !|ALICE.RSC must be|in current directory][ Abort ]",
/* 376 */   "[1][%ld bytes free][ OK ]",
/* 377 */   "Answer string",
/* 378 */   nl,
/* 379 */   nl,
/* 380 */   nl,
/* 381 */   nl,
/* 382 */   "maximum of 128 points allowed",
/* 383 */   "Bus Error",
/* 384 */   "Address Error",
/* 385 */   "Illegal Instruction",
/* 386 */   "Privilege Violation",
/* 387 */   "Divide By Zero",
/* 388 */   "[2][Fatal Error %d !|%s at %c%lx|Save Workspaces|Immediately !][ OK | Abort ]",
/* 389 */   nl,
/* 390 */   "[2][Could not change directory][ OK ]",
/* 391 */   "[2][Error ! - Not enough|memory to run ALICE][ OK ]",
/* 392 */   "[2][Not enough memory|to resize window][ OK ]",
/* 393 */   "[2][Caution: Not enough memory|to buffer new graphics|window][ OK ]",
/* 394 */   "[2][You have not saved this|workspace. Close it|anyway?][ Yes | No ]",
/* 395 */   nl,
/* 396 */   "Untitled",
/* 397 */   " main ",
/* 398 */   "[2][%s][ OK | HELP ]",
/* 399 */   "[2][%s][ OK ]",
/* 400 */   "A runtime error has occured\n",
/* 401 */   "Built in Names",
/* 402 */   "Symbols",
/* 403 */   " <Built in Names> ",
/* 404 */   nl,
/* 405 */   "Builtin Symbols",
/* 406 */   nl,
/* 407 */   "Undefined",
/* 408 */   "Sorry, can't elaborate any further on the last message",
/* 409 */   "Change this to:",
/* 410 */   "System Command: ",
/* 411 */   "Save Interval (0 for no Autosave) ? ",
/* 412 */   "[2][Typecheck completed.|No errors detected.][ OK ]",
/* 413 */   nl,
/* 414 */   "Option line? ",
/* 415 */   "Name of output file:",
/* 416 */   "Command Help",
/* 417 */   "[2][Click on OKAY to|return to ALICE][ OK ]",
/* 418 */   "Command Line? ",
/* 419 */   "square",
/* 420 */   "StrConcat first argument",
/* 421 */   "String Delete string",
/* 422 */   "String Insert string",
/* 423 */   "SubStr destination string",
/* 424 */   "Integer? ",
/* 425 */   "Real Number? ",
/* 426 */   "Character? ",
/* 427 */   "String? ",
/* 428 */   "Break!",
/* 429 */   "Comment? ",
/* 430 */   "Possible Input",
/* 431 */   "Pascal Help",
/* 432 */   "[2][This operation is too|involved to UNDO|Do it anyway ?][ OK | CANCEL ]",
/* 433 */   "Scalar := %s",
/* 434 */   "Integer := %d",
/* 435 */   "Real := %g",
/* 436 */   "String := \"%s\"",
/* 437 */   "addition",
/* 438 */   "multiplication",
/* 439 */   "Expansion: ",
/* 440 */   "[2][You have not saved|this workspace|Load anyway ?][ Yes | No ]",
/* 441 */   "can't open library \"%s\"\n",
/* 442 */   "Bad library save format (%s)",
/* 443 */   "Bad save format (%s)\n",
/* 444 */   "not an ALICE Pascal save file",
/* 445 */   "unsupported version",
/* 446 */   "wrong sized integers",
/* 447 */   "bad symbol table",
/* 448 */   "premature end of file",
/* 449 */   "Use: %s [file] [C=confile] [s=varstacksize] [f=checking freq]\n             [l=locstacksize] [m#=macrostring]* [c#=fontcode]* [-indent]\n",
/* 450 */   "Error on startup of ALICE\n",
/* 451 */   "Error in loading templates\n",
/* 452 */   "[2][You have not saved one|of your workspaces|Quit anyway ?][ Yes | No ]",
/* 453 */   "[2][You have not saved one|of your workspaces|Quit anyway ?][ Quit | Don't Quit ]",
/* 454 */   "subtraction",
/* 455 */   "Mark? ",
/* 456 */   nl,
/* 457 */   nl,
/* 458 */   nl,
/* 459 */   nl,
/* 460 */   "Sorry, '%s' isn't a valid number, please try again",
/* 461 */   nl,
/* 462 */   "<EOF>\n",
/* 463 */   nl,
/* 464 */   "Str destination",
/* 465 */   "[2][That file already exists !|Should it be overwritten ?][ OK | CANCEL ]",
/* 466 */   "Directory String",
/* 467 */   "Filename String",
/* 468 */   nl,
/* 469 */   nl,
/* 470 */   "Internal error: ",
/* 471 */   "[2][An Internal Error has occurred|Continue ?][ OK | Abort ]",
/* 472 */   "",
/* 473 */   "Frame %2.2d/%2.2d in ",
/* 474 */   nl,
/* 475 */   "<Program>",
/* 476 */   "<Immediate>",
/* 477 */   "Suspend",
/* 478 */   "Command:",
/* 479 */   "[2][Clearing a workspace|cannot be undone|Do it anyway?][ Yes | No ]",
/* 480 */   "Workspaces",
/* 481 */   "Workspace Name? ",
/* 482 */   "SUSPEND",
/* 483 */   "New Workspace",

/* Short form of Menu, for low-rez */

/* 484 */   "Dsk ",
/* 485 */   "File ",
/* 486 */   "Ed ",
/* 487 */   "Stc ",
/* 488 */   "Run ",
/* 489 */   "Dbg ",
/* 490 */   "Help ",
/* 491 */   "Go ",
/* 492 */   "Misc",
/* 493 */   "[2][Break !|Continue Execution ?][ Yes | No ]",

	    nl };

#define MAX_ERR	492

char *
getERRstr( num )
int num;
{
	char *str;
	char msg[60];
	char *n = "<Nil>";

	if( num > MAX_ERR ) {
		sprintf( msg, "[2][Error - error msg %d][ OK ]", num );
		form_alert( 1, msg );
		return n;
	}
	str = ErrStrs[num];
	if( *str == 0 ) {
		sprintf( msg, "[2][Error - null msg %d][ OK ]", num );
		form_alert( 1, msg );
		return n;
	}
	return str;
}

char *
getLDSstr( num )
int num;
{
	return getERRstr( num );
}

#ifdef TEST
main()
{
	int i;

	for( i=0; i <= MAX_ERR; i++ ) {
		printf( "%3d \"%s\"\n", i, ErrStrs[i] );
	}
}
#endif TEST
