extern	NodeNum	ntype(void *);
extern	void	s_ntype(void *,NodeNum);
extern	holdlist	node_flag(void *);
extern	holdlist	listcount(nodep);
extern	void	s_node_flag(void *,holdlist);
extern	void	s_listcount(void *,holdlist);
extern	void	or_node_flag(void *,holdlist);
extern	void	clr_node_flag(void *,holdlist);
extern	holdlist	node_2flag(void *);
extern	holdlist	listacount(nodep);
extern	void	s_2flag(void *,holdlist);
extern	void	s_listacount(nodep,holdlist);
extern	void	or_2flag(void *,holdlist);
extern	void	clr_2flag(void *,holdlist);
extern	nodep	node_parent(nodep);
extern	nodep	tparent(void *);
extern	nodep	listparent(nodep);
extern	nodep	sym_declaration(symptr);
extern	void	s_node_parent(nodep,nodep);
extern	void	s_tparent(void *,nodep);
extern	void	s_listparent(nodep,nodep);
extern	void	s_sym_declaration(symptr,nodep);
extern	nodep	kid1(nodep);
extern	symptr	kid_id(nodep);
extern	nodep	kid2(nodep);
extern	nodep	kid3(nodep);
extern	nodep	kid4(nodep);
extern	nodep	kid5(nodep);
extern	nodep	kid6(nodep);
extern	nodep	kid7(nodep);
extern	nodep	kid8(nodep);
extern	int	int_kid(int,nodep);
extern	char *	str_kid(int,nodep);
extern	nodep	node_kid(nodep,int);
extern	void	s_int_kid(int,nodep,int);
extern	void	s_str_kid(int,nodep,unsigned);
extern	void	s_node_kid(nodep,int,nodep);
extern	void	s_kid1(nodep,nodep);
extern	void	s_kid_id(nodep,symptr);
extern	void	s_kid2(nodep,nodep);
extern	void	s_kid3(nodep,nodep);
extern	void	s_kid4(nodep,nodep);
extern	void	s_kid5(nodep,nodep);
extern	void	s_kid6(nodep,nodep);
extern	void	s_kid7(nodep,nodep);
extern	void	s_kid8(nodep,nodep);
extern	char *	sym_name(symptr);
extern	bits8	sym_nhash(symptr);
extern	bits8	sym_mflags(symptr);
extern	nodep	sym_type(symptr);
extern	symptr	sym_next(symptr);
extern	int	sym_offset(symptr);
extern	int	sym_ivalue(symptr);
extern	int	sym_framesize(symptr);
extern	pint	sym_value(symptr);
extern	short	sym_size(symptr);
extern	bits8	sym_dtype(symptr);
extern	bits8	sym_scope(symptr);
extern	short	sym_saveid(symptr);
extern	void	s_sym_name(symptr, char *);
extern	void	s_sym_nhash(symptr, bits8);
extern	void	s_sym_mflags(symptr, bits8);
extern	void	or_sym_mflags(symptr, bits8);
extern	void	clr_sym_mflags(symptr, bits8);
extern	void	s_sym_type(symptr, nodep);
extern	void	s_sym_next(symptr, symptr);
extern	void	s_sym_offset(symptr, int);
extern	void	s_sym_ivalue(symptr, int);
extern	void	s_sym_framesize(symptr, int);
extern	void	s_sym_dtype(symptr, type_code);
extern	void	s_sym_value(symptr, pint);
extern	void	s_sym_size(symptr, short);
extern	void	s_sym_scope(symptr, bits8);
extern	void	s_sym_saveid(symptr, short);
extern	nodep	barglist(nodep,int,int);
extern nodep far * kid1adr(nodep);
